# Numpyの基本

In [4]:
import numpy as np

In [5]:
int_array = np.arange(10).reshape((2, 5))
print(int_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## 初期化

In [6]:
ar = np.zeros((2,5))
print(ar)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
